version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:lasted
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: docker/dev/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306
